require_relative 'config/environment'
require "sinatra/activerecord/rake"

desc 'Will load a console with the environment'
task :console do
  def reload!
    load_all 'app'
  end
  
  Pry.start
end

desc 'Generate a static site in _site'
task :generate do
  require 'fileutils'
  require 'erb'
  SiteGenerator.new.call
end