# A sample Gemfile
source "https://rubygems.org"

# gem "rails"
gem 'rake'
gem 'pry'
gem 'sqlite3'
gem 'require_all'
gem 'rspec'
gem 'activerecord', :require => "active_record"
gem 'sinatra-activerecord'